version: '3.8'
services:
  mockoon:
    image: mockoon/cli:latest
    command: --data data --port 3000
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: threedee.json
        target: /data
        read_only: true

