//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeDeeFrontend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreeDeeFrontend.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        internal static string AppErrorAddress {
            get {
                return ResourceManager.GetString("AppErrorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Private Files.
        /// </summary>
        internal static string ComponentsFileAccessFilterPrivateFiles {
            get {
                return ResourceManager.GetString("ComponentsFileAccessFilterPrivateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Public Files.
        /// </summary>
        internal static string ComponentsFileAccessFilterPublicFiles {
            get {
                return ResourceManager.GetString("ComponentsFileAccessFilterPublicFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Shared Files.
        /// </summary>
        internal static string ComponentsFilesAccessFilterSharedFiles {
            get {
                return ResourceManager.GetString("ComponentsFilesAccessFilterSharedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string ComponentsGCodeTableAuthor {
            get {
                return ResourceManager.GetString("ComponentsGCodeTableAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string ComponentsGCodeTableDetails {
            get {
                return ResourceManager.GetString("ComponentsGCodeTableDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filament used in m.
        /// </summary>
        internal static string ComponentsGCodeTableFilamentLengthUsed {
            get {
                return ResourceManager.GetString("ComponentsGCodeTableFilamentLengthUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing Time in min.
        /// </summary>
        internal static string ComponentsGCodeTablePrintingTime {
            get {
                return ResourceManager.GetString("ComponentsGCodeTablePrintingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ComponentsGCodeTableSuccess {
            get {
                return ResourceManager.GetString("ComponentsGCodeTableSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in available models.
        /// </summary>
        internal static string ComponentsSearchBarLabel {
            get {
                return ResourceManager.GetString("ComponentsSearchBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new file.
        /// </summary>
        internal static string DropDownAddFile {
            get {
                return ResourceManager.GetString("DropDownAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private files.
        /// </summary>
        internal static string DropDownPrivateFiles {
            get {
                return ResourceManager.GetString("DropDownPrivateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all files.
        /// </summary>
        internal static string DropDownPublicFiles {
            get {
                return ResourceManager.GetString("DropDownPublicFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request new model.
        /// </summary>
        internal static string DropDownRequestFile {
            get {
                return ResourceManager.GetString("DropDownRequestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shared files.
        /// </summary>
        internal static string DropDownSharedFiles {
            get {
                return ResourceManager.GetString("DropDownSharedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string PagesFileCardComments {
            get {
                return ResourceManager.GetString("PagesFileCardComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created by:.
        /// </summary>
        internal static string PagesFileCardCreatedBy {
            get {
                return ResourceManager.GetString("PagesFileCardCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string PagesFileCardDownload {
            get {
                return ResourceManager.GetString("PagesFileCardDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCode.
        /// </summary>
        internal static string PagesFileCardGCode {
            get {
                return ResourceManager.GetString("PagesFileCardGCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new Comment.
        /// </summary>
        internal static string PagesFileCardNewComment {
            get {
                return ResourceManager.GetString("PagesFileCardNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string PagesFileCardOn {
            get {
                return ResourceManager.GetString("PagesFileCardOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload GCode.
        /// </summary>
        internal static string PagesFileCardUploadGCode {
            get {
                return ResourceManager.GetString("PagesFileCardUploadGCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string PagesGCodeAnalyzerDownload {
            get {
                return ResourceManager.GetString("PagesGCodeAnalyzerDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string PagesIndexTitle {
            get {
                return ResourceManager.GetString("PagesIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has occurred. See browser dev tools for details..
        /// </summary>
        internal static string PagesLayoutDevError {
            get {
                return ResourceManager.GetString("PagesLayoutDevError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. This application may no longer respond until reloaded..
        /// </summary>
        internal static string PagesLayoutProdError {
            get {
                return ResourceManager.GetString("PagesLayoutProdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string PagesLayoutReload {
            get {
                return ResourceManager.GetString("PagesLayoutReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string SharedLoginLogIn {
            get {
                return ResourceManager.GetString("SharedLoginLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string SharedLoginLogOut {
            get {
                return ResourceManager.GetString("SharedLoginLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string SharedLoginRegister {
            get {
                return ResourceManager.GetString("SharedLoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string SharedLoginWelcomeText {
            get {
                return ResourceManager.GetString("SharedLoginWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DARK.
        /// </summary>
        internal static string SharedMainDarkModeDark {
            get {
                return ResourceManager.GetString("SharedMainDarkModeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIGHT.
        /// </summary>
        internal static string SharedMainDarkModeLight {
            get {
                return ResourceManager.GetString("SharedMainDarkModeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string SharedMainDropDownFiles {
            get {
                return ResourceManager.GetString("SharedMainDropDownFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string SharedMainDropDownLibrary {
            get {
                return ResourceManager.GetString("SharedMainDropDownLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D File Management System.
        /// </summary>
        internal static string SharedMainPageTitle {
            get {
                return ResourceManager.GetString("SharedMainPageTitle", resourceCulture);
            }
        }
    }
}
