//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeDeeFrontend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreeDeeFrontend.Localization.de", typeof(Localization_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, unter dieser Adresse gibt es nichts..
        /// </summary>
        internal static string App_ErrorAddress {
            get {
                return ResourceManager.GetString("App_ErrorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Dateien anzeigen.
        /// </summary>
        internal static string Components_FileAccessFilter_PrivateFiles {
            get {
                return ResourceManager.GetString("Components_FileAccessFilter_PrivateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentliche Dateien anzeigen.
        /// </summary>
        internal static string Components_FileAccessFilter_PublicFiles {
            get {
                return ResourceManager.GetString("Components_FileAccessFilter_PublicFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigegebene Dateien anzeigen.
        /// </summary>
        internal static string Components_FilesAccessFilter_SharedFiles {
            get {
                return ResourceManager.GetString("Components_FilesAccessFilter_SharedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor/-in.
        /// </summary>
        internal static string Components_GCodeTable_Author {
            get {
                return ResourceManager.GetString("Components_GCodeTable_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Components_GCodeTable_Details {
            get {
                return ResourceManager.GetString("Components_GCodeTable_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filament verwendet in m.
        /// </summary>
        internal static string Components_GCodeTable_FilamentLengthUsed {
            get {
                return ResourceManager.GetString("Components_GCodeTable_FilamentLengthUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druckzeit in min.
        /// </summary>
        internal static string Components_GCodeTable_PrintingTime {
            get {
                return ResourceManager.GetString("Components_GCodeTable_PrintingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolg.
        /// </summary>
        internal static string Components_GCodeTable_Success {
            get {
                return ResourceManager.GetString("Components_GCodeTable_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche in verfügbaren Modellen.
        /// </summary>
        internal static string Components_SearchBar_Label {
            get {
                return ResourceManager.GetString("Components_SearchBar_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei hinzufügen.
        /// </summary>
        internal static string DropDownAddFile {
            get {
                return ResourceManager.GetString("DropDownAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private Dateien.
        /// </summary>
        internal static string DropDownPrivateFiles {
            get {
                return ResourceManager.GetString("DropDownPrivateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alle Dateien.
        /// </summary>
        internal static string DropDownPublicFiles {
            get {
                return ResourceManager.GetString("DropDownPublicFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neues Modell anfordern.
        /// </summary>
        internal static string DropDownRequestFile {
            get {
                return ResourceManager.GetString("DropDownRequestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geteilte Dateien.
        /// </summary>
        internal static string DropDownSharedFiles {
            get {
                return ResourceManager.GetString("DropDownSharedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentare.
        /// </summary>
        internal static string Pages_FileCard_Comments {
            get {
                return ResourceManager.GetString("Pages_FileCard_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to erstellt von:.
        /// </summary>
        internal static string Pages_FileCard_CreatedBy {
            get {
                return ResourceManager.GetString("Pages_FileCard_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herunterladen.
        /// </summary>
        internal static string Pages_FileCard_Download {
            get {
                return ResourceManager.GetString("Pages_FileCard_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCode.
        /// </summary>
        internal static string Pages_FileCard_GCode {
            get {
                return ResourceManager.GetString("Pages_FileCard_GCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neues Kommentar.
        /// </summary>
        internal static string Pages_FileCard_newComment {
            get {
                return ResourceManager.GetString("Pages_FileCard_newComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to am.
        /// </summary>
        internal static string Pages_FileCard_on {
            get {
                return ResourceManager.GetString("Pages_FileCard_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCode hochladen.
        /// </summary>
        internal static string Pages_FileCard_UploadGCode {
            get {
                return ResourceManager.GetString("Pages_FileCard_UploadGCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herunterladen.
        /// </summary>
        internal static string Pages_GCodeAnalyzer_Download {
            get {
                return ResourceManager.GetString("Pages_GCodeAnalyzer_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateien.
        /// </summary>
        internal static string Pages_Index_Title {
            get {
                return ResourceManager.GetString("Pages_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine nicht behandelte Ausnahme aufgetreten. Einzelheiten finden Sie unter Browser-Entwicklungstools..
        /// </summary>
        internal static string Pages_Layout_DevError {
            get {
                return ResourceManager.GetString("Pages_Layout_DevError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Fehler ist aufgetreten. Diese Anwendung reagiert möglicherweise nicht mehr, bis sie neu geladen wird..
        /// </summary>
        internal static string Pages_Layout_ProdError {
            get {
                return ResourceManager.GetString("Pages_Layout_ProdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neu laden.
        /// </summary>
        internal static string Pages_Layout_Reload {
            get {
                return ResourceManager.GetString("Pages_Layout_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen.
        /// </summary>
        internal static string Shared_Login_LogIn {
            get {
                return ResourceManager.GetString("Shared_Login_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausloggen.
        /// </summary>
        internal static string Shared_Login_LogOut {
            get {
                return ResourceManager.GetString("Shared_Login_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        internal static string Shared_Login_Register {
            get {
                return ResourceManager.GetString("Shared_Login_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo.
        /// </summary>
        internal static string Shared_Login_WelcomeText {
            get {
                return ResourceManager.GetString("Shared_Login_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNKEL.
        /// </summary>
        internal static string Shared_Main_DarkMode_Dark {
            get {
                return ResourceManager.GetString("Shared_Main_DarkMode_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELL.
        /// </summary>
        internal static string Shared_Main_DarkMode_Light {
            get {
                return ResourceManager.GetString("Shared_Main_DarkMode_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateien.
        /// </summary>
        internal static string Shared_Main_DropDown_Files {
            get {
                return ResourceManager.GetString("Shared_Main_DropDown_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothek.
        /// </summary>
        internal static string Shared_Main_DropDown_Library {
            get {
                return ResourceManager.GetString("Shared_Main_DropDown_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Dateien Management System.
        /// </summary>
        internal static string Shared_Main_PageTitle {
            get {
                return ResourceManager.GetString("Shared_Main_PageTitle", resourceCulture);
            }
        }
    }
}
