//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeDeeFrontend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreeDeeFrontend.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        internal static string App_ErrorAddress {
            get {
                return ResourceManager.GetString("App_ErrorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new file.
        /// </summary>
        internal static string DropDownAddFile {
            get {
                return ResourceManager.GetString("DropDownAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private files.
        /// </summary>
        internal static string DropDownPrivateFiles {
            get {
                return ResourceManager.GetString("DropDownPrivateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all files.
        /// </summary>
        internal static string DropDownPublicFiles {
            get {
                return ResourceManager.GetString("DropDownPublicFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request new model.
        /// </summary>
        internal static string DropDownRequestFile {
            get {
                return ResourceManager.GetString("DropDownRequestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shared files.
        /// </summary>
        internal static string DropDownSharedFiles {
            get {
                return ResourceManager.GetString("DropDownSharedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Pages_FileCard_Comments {
            get {
                return ResourceManager.GetString("Pages_FileCard_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created by:.
        /// </summary>
        internal static string Pages_FileCard_CreatedBy {
            get {
                return ResourceManager.GetString("Pages_FileCard_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Pages_FileCard_Download {
            get {
                return ResourceManager.GetString("Pages_FileCard_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCode.
        /// </summary>
        internal static string Pages_FileCard_GCode {
            get {
                return ResourceManager.GetString("Pages_FileCard_GCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new Comment.
        /// </summary>
        internal static string Pages_FileCard_newComment {
            get {
                return ResourceManager.GetString("Pages_FileCard_newComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string Pages_FileCard_on {
            get {
                return ResourceManager.GetString("Pages_FileCard_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload GCode.
        /// </summary>
        internal static string Pages_FileCard_UploadGCode {
            get {
                return ResourceManager.GetString("Pages_FileCard_UploadGCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Pages_GCodeAnalyzer_Download {
            get {
                return ResourceManager.GetString("Pages_GCodeAnalyzer_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Pages_Index_Title {
            get {
                return ResourceManager.GetString("Pages_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has occurred. See browser dev tools for details..
        /// </summary>
        internal static string Pages_Layout_DevError {
            get {
                return ResourceManager.GetString("Pages_Layout_DevError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. This application may no longer respond until reloaded..
        /// </summary>
        internal static string Pages_Layout_ProdError {
            get {
                return ResourceManager.GetString("Pages_Layout_ProdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Pages_Layout_Reload {
            get {
                return ResourceManager.GetString("Pages_Layout_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Shared_Login_LogIn {
            get {
                return ResourceManager.GetString("Shared_Login_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Shared_Login_LogOut {
            get {
                return ResourceManager.GetString("Shared_Login_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Shared_Login_Register {
            get {
                return ResourceManager.GetString("Shared_Login_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Shared_Login_WelcomeText {
            get {
                return ResourceManager.GetString("Shared_Login_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DARK.
        /// </summary>
        internal static string Shared_Main_DarkMode_Dark {
            get {
                return ResourceManager.GetString("Shared_Main_DarkMode_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIGHT.
        /// </summary>
        internal static string Shared_Main_DarkMode_Light {
            get {
                return ResourceManager.GetString("Shared_Main_DarkMode_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Shared_Main_DropDown_Files {
            get {
                return ResourceManager.GetString("Shared_Main_DropDown_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Shared_Main_DropDown_Library {
            get {
                return ResourceManager.GetString("Shared_Main_DropDown_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D File Management System.
        /// </summary>
        internal static string Shared_Main_PageTitle {
            get {
                return ResourceManager.GetString("Shared_Main_PageTitle", resourceCulture);
            }
        }
    }
}
