//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeDeeFrontend {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreeDeeFrontend.Localization.de", typeof(Localization_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei hinzufügen.
        /// </summary>
        internal static string DropDownAddFile {
            get {
                return ResourceManager.GetString("DropDownAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private Dateien.
        /// </summary>
        internal static string DropDownPrivateFiles {
            get {
                return ResourceManager.GetString("DropDownPrivateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alle Dateien.
        /// </summary>
        internal static string DropDownPublicFiles {
            get {
                return ResourceManager.GetString("DropDownPublicFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neues Modell anfordern.
        /// </summary>
        internal static string DropDownRequestFile {
            get {
                return ResourceManager.GetString("DropDownRequestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geteilte Dateien.
        /// </summary>
        internal static string DropDownSharedFiles {
            get {
                return ResourceManager.GetString("DropDownSharedFiles", resourceCulture);
            }
        }
    }
}
